application:
  user:
    name: JEFFREY CHU
    role: Senior Engineer, Backend
    company: Moxbank
    tribe: Cards & Lending
    group:
      - Technology
    departmentRoles:
      Credit Risk:
        - Backend Engineer
        - Vault-Admin


