application:
  user:
    name: JEFFREY CHU Test
    role: Developer
    team: CARGOSMART/B2B
    group:
      - application_owner
      - product_owner
    departmentRoles:
      ISD:
        - Developer
        - Assistant Technical Analyst

